WOMEN_BUTTON="//*[@id='ui-id-2']/li[2]"
WIDGET_PRODUCT_1="//*[@id='maincontent']/div[4]/div[1]/div[1]/div[3]/div/div/ol/li[1]"
WIDGET_PRODUCT_2="//*[@id='maincontent']/div[4]/div[1]/div[1]/div[3]/div/div/ol/li[2]"
WIDGET_PRODUCT_3="//*[@id='maincontent']/div[4]/div[1]/div[1]/div[3]/div/div/ol/li[3]"
SIZE_BUTTON_XS = "//*[@id='option-label-size-143-item-166']"
COLLOR_BUTTON_BLUE="//*[@id='option-label-color-93-item-50']"
COLLOR_BUTTON_PURPLE="//*[@id='option-label-color-93-item-57']"
ADD_CART_BUTTON="//*[@id='product-addtocart-button']"
CART_BUTTON="//a[@class='action showcart' and @href='https://magento.softwaretestingboard.com/checkout/cart/']"
CHECKOUT_BUTTON="//button[@id='top-cart-btn-checkout' and @class='action primary checkout' and @data-action='close' and @title='Proceed to Checkout']"
ADDED_ELEMENT="//*[@id='maincontent']/div[1]/div[2]/div/div/div"
EMAIL_FORM= "//*[@id='customer-email']"
SIGN_BUTTON="/html/body/div[2]/header/div[1]/div/ul/li[2]/a"
SIGN_EMAIL_FORM="//*[@id='email']"
PASS="//*[@id='pass']"
SUBMIT_SIGN="//*[@id='send2']"
STREET_ADDRESS_CHECKOUT_FORM="//input[@name='street[0]']"
CITY_CHECKOUT_FORM="//input[@name='city']"
ZIP_CHECKOUT_FORM="//input[@name='postcode']"
INDONESIA="//select[@name='country_id']/option[@data-title='Indonesia']"
PHONE_CHECKOUT_FORM="//input[@name='telephone']"
NEXT_CHEKOUT_BUTTON="//*[@id='shipping-method-buttons-container']/div/button"
PLACE_ORDER_BUTTON_CHECKOUT="//button[contains(@title, 'Place Order')]//span[contains(text(), 'Place Order')]"
NEXT_BUTTON="//*[@id='shipping-method-buttons-container']/div/button"
THANKS_ELEMENT="//span[@class='base' and @data-ui-id='page-title-wrapper']"
PHONE_ELEMENT="//*[@id='checkout-step-shipping']/div[1]/div/div/div/a"